import {
    FOLLOW_LINK_MESSAGE,
    IS_MANDATORY_MESSAGE,
    LAST_MONTH_RANGE_TEXT,
    NO_OPTIONS_MESSAGE,
    OPEN_MESSAGE,
    RESET_MESSAGE,
    SHOW_PASSWORD_MESSAGE,
    THIS_MONTH_RANGE_TEXT,
    THIS_YEAR_RANGE_TEXT,
    TODAY_RANGE_TEXT
} from "../constants";

export class LktFieldsSettings {

    /**
     * Common texts
     */
    static SHOW_PASSWORD_MESSAGE = SHOW_PASSWORD_MESSAGE;
    static IS_MANDATORY_MESSAGE = IS_MANDATORY_MESSAGE;
    static FOLLOW_LINK_MESSAGE = FOLLOW_LINK_MESSAGE;
    static OPEN_MESSAGE = OPEN_MESSAGE;
    static RESET_MESSAGE = RESET_MESSAGE;

    /**
     * Fields with options
     */
    static NO_OPTIONS_MESSAGE = NO_OPTIONS_MESSAGE;

    /**
     * Date ranges
     */
    static TODAY_RANGE_TEXT = TODAY_RANGE_TEXT;
    static THIS_MONTH_RANGE_TEXT = THIS_MONTH_RANGE_TEXT;
    static LAST_MONTH_RANGE_TEXT = LAST_MONTH_RANGE_TEXT;
    static THIS_YEAR_RANGE_TEXT = THIS_YEAR_RANGE_TEXT;
}